name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables for Vite
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ vars.VITE_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_APP_ID=${{ vars.VITE_FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_DATABASE_URL=${{ vars.VITE_FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ vars.VITE_FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_PROJECT_ID=${{ vars.VITE_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV

          echo "VITE_EMAILJS_SERVICE_ID=${{ vars.VITE_EMAILJS_SERVICE_ID }}" >> $GITHUB_ENV
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ vars.VITE_EMAILJS_TEMPLATE_ID }}" >> $GITHUB_ENV
          echo "VITE_EMAILJS_FILE_TEMPLATE_ID=${{ vars.VITE_EMAILJS_FILE_TEMPLATE_ID }}" >> $GITHUB_ENV
          echo "VITE_EMAILJS_USER_ID=${{ vars.VITE_EMAILJS_USER_ID }}" >> $GITHUB_ENV
          echo "VITE_ADMIN_USER_ID=${{ vars.VITE_ADMIN_USER_ID }}" >> $GITHUB_ENV

      - name: Install and build
        run: npm install && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UTVEKSLING_DATABASE }}
          channelId: live
          projectId: utveksling-database
